language: generic 
sudo: required
services:
  - docker
before_install:
    - docker build -t amitdocker/docker-react3 -f Dockerfile.dev .
scripts:
  - docker run -e CI=true amitdocker/docker-react3 npm run test